### ISSUE TITLE
Addressing review

### ISSUE THREAD

**Issue by Crembotz** [rematocorp/trello-integration-action#112]
Hi.
I was wondering if it would be possible to add the functionality to move Trello tasks to different columns based on the latest submitted review, for example:
If I submitted a review for a PR and I requested for changes to be made then I'd like to move the card to a certain list and if I submitted a review for a PR and I approved it then I'd like to move it to a different list.

Thanks!

**Comment by ukupat** [comment]
Hi! Yes, I think this is possible. What if there are multiple reviews, for example: one approves and the other requests changes. Do I assume correctly that then the action should move the Trello task to the "Changes required" list?

Here is the full list of review statuses https://docs.github.com/en/graphql/reference/enums#pullrequestreviewstate. Could you please outline me how do you want to manage your Trello tasks based on different situations? I'm more than happy to implement it.

**Comment by Crembotz** [comment]
So the way we do things is as follows:
We create a new PR and the card is moved to a list called **pending for a review**.
A team member goes through the PR and submits it with the `request changes` option, then we would move the card to a list called **pending for fixes** - in this case the relevant value from the enum would be `REQUEST_CHANGES`
After the person assigned on the task addressed the comments made, we would move back the card to **pending for a review** list.
This would go on until the PR is approved, in this case the card would be moved to the **Approved** list.
After the branch was merged, we would move the card to the **Done** list.
Hope this clears things up.

**Comment by ukupat** [comment]
Thank you! One more question:

> After the person assigned to the task addressed the comments made

Does this mean that the person clicks on the "Re-request review" button? Or something else?

<img width="410" alt="Screenshot 2024-07-04 at 08 03 28" src="https://github.com/rematocorp/trello-integration-action/assets/4997766/1381fae5-df6d-4376-bfa7-147cbbe33c8e">

**Comment by Crembotz** [comment]
I'll admit that up until now we've just notified each other via a group chat but your suggestion is the better alternative and the approach we'll take from now on :)

**Comment by ukupat** [comment]
Hehe cool, we use this little button too :) I'll try to implement your feature request soon. I'll let you know when you can test it out!

**Comment by Crembotz** [comment]
Thank you so much!

**Comment by ukupat** [comment]
@Crembotz aaalright, please test v9.5.0, it includes these changes https://github.com/rematocorp/trello-integration-action/pull/113/files. Let me know if you need help or if something is not working correctly :)

**Comment by Crembotz** [comment]
You are incredible, you've done it really really fast!
I'll try it out tomorrow and let you know of my findings, thank you so much!

**Comment by Crembotz** [comment]
@ukupat I've ran my tests and everything exactly as I expected, thank you so much for getting this done, this will be a huge help!
One note about the readme file: in the sections of the fields `trello-list-id-pr-changes-requested` and `trello-list-id-pr-approved` you said that you need to add the `review_requested` and `review_request_removed` types to `pull_request_review` trigger. After checking the documentation, the types associated with this trigger are `submitted`, `edited` and `dismissed` so you should update the readme file.
Thanks again for your help!

**Comment by ukupat** [comment]
I actually meant this
<img width="396" alt="Screenshot 2024-07-05 at 12 44 41" src="https://github.com/rematocorp/trello-integration-action/assets/4997766/560621f9-e207-42eb-9ec4-13ab9d8878a3">

I will try to improve the readme, thanks for the feedback :) I'm glad it works. Let me know if your team finds some anomalies :)

**Comment by Crembotz** [comment]
So `pull_request_review` is supposed to stay empty?

**Comment by ukupat** [comment]
I believe

```
pull_request_review:
```

equals

```
pull_request_review:
    types: [submitted, edited, dismissed]
```
 so it is up to you if you want to write the types out or not :)
