### ISSUE TITLE
Bug: Cannot read properties of undefined (reading 'some')

### ISSUE THREAD

**Issue by andybardagi** [rematocorp/trello-integration-action#121]
Hello! Recently we have some trouble with our multiboard organization working. I read the latest version changelog (Improve finding a correct card based on the branch name when dealing with multi-board orgs) and think this version could fix it. We did the upgrade and now we always get an error the following error 

```
--- FIND CARDS ---
Searching cards from branch name feat/34-xxxxxxxx
Matched one potential card from branch name [
  '34-xxxxxxxx',
  '34',
  'xxxxxxxx',
  index: 5,
  input: 'xxxxxxxx',
  groups: undefined
]
Error: TypeError: Cannot read properties of undefined (reading 'some')
/home/runner/work/_actions/rematocorp/trello-integration-action/v9.6.2/dist/index.js:34495
        card.actions.some((action) => action.data.card.idShort === parseInt(shortId)))?.shortLink;
```

Just for context:
- action version: 9.6.2 
- 1 workspace with 3 boards

I submitted a PR #120  but not really sure how it can impact on the action behavior.

**Comment by ukupat** [comment]
Thanks again! :)

**Comment by ukupat** [comment]
I ended up with [this solution](https://github.com/rematocorp/trello-integration-action/commit/9a469a8e3d6d6983a693fad61280f3c57a51becc). I could swear that Trello API returned `actions` with ["Get a card" endpoint](https://developer.atlassian.com/cloud/trello/rest/api-group-cards/#api-cards-id-get) by default... but maybe I misunderstood.

**Comment by ukupat** [comment]
> Recently we have some trouble with our multiboard organization working

Try upgrading to v9.6.4 and let me know if you still have problems, @andybardagi :)

**Comment by andybardagi** [comment]
Works without problems! Thank you @ukupat !

**Comment by ukupat** [comment]
Great to hear that!
