### ISSUE TITLE
Consider author + assignees for Trello card assignment?

### ISSUE THREAD

**Issue by geoffharcourt** [rematocorp/trello-integration-action#21]
Hi! This is an awesome action. I noticed that the assignment of membership on the Trello card is dependent on the PR having the same assignees. Would you be open to including authors in that listing as well?

**Comment by ukupat** [comment]
Hi! Thanks!

Currently, the system works like this:
1. Get PR author and assignees
2. Find Trello users with the same Github user names (can be configured to only include users who have access to your Trello org)
3. If found then remove all card members that weren't found in step 2
4. Add members that were found in step 2

By "including authors in that listing as well" do you mean skipping the 3rd step?

**Comment by geoffharcourt** [comment]
Ah, I think I was less astray by the output that said "assignees". 

I have the same Trello and GitHub usernames (and I'm a board member and org admin) and am not getting attached to cards when their link is found (and the attachment is added). Any ideas?

**Comment by ukupat** [comment]
Good question. Maybe if you could share your actions log then we can figure it out:

<img width="203" alt="Screen Shot 2022-06-05 at 14 05 21" src="https://user-images.githubusercontent.com/4997766/172047663-060fb770-b7e5-4c4a-b87a-f2557a54ff56.png">
