### ISSUE TITLE
401 unauthorized

### ISSUE THREAD

**Issue by alfredbirk** [rematocorp/trello-integration-action#52]
Getting 401 unauthorized. Here is the action log
```
Run rematocorp/trello-integration-action@v6.3.1
Requesting pull request comments
Requesting pull request assignees
Searching for card ids
Found card IDs [ 'MLk6AYxO' ]
Skipping moving the cards open draft
Checking existing attachments MLk6AYxO
Error 401 Unauthorized https://api.trello.com/1/cards/MLk6AYxO/attachments
Adding attachment to the card MLk6AYxO https://github.com/orgname/my-repo/pull/3988
Error 401 Unauthorized https://api.trello.com/1/cards/MLk6AYxO/attachments
Starting to update card members
Searching Trello member id by username alfredbirk
Error 401 Unauthorized https://api.trello.com/1/members/alfredbirk
No Trello members found based on PR assignees
Starting to add labels to cards
Getting card info MLk6AYxO
Error 401 Unauthorized https://api.trello.com/1/cards/MLk6AYxO
/home/runner/work/_actions/rematocorp/trello-integration-action/v6.3.1/dist/index.js:[16](https://github.com/orgname/my-repo//actions/runs/5321480183/jobs/9637190611#step:2:17)905
		const hasConflictingLabel = cardInfo.labels.find(
		                                     ^

TypeError: Cannot read properties of undefined (reading 'labels')
    at /home/runner/work/_actions/rematocorp/trello-integration-action/v6.3.1/dist/index.js:16905:40
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
```

What is confusing me is that it seems to be able to find the correct card ID. But for some reason it is getting unauthorized for other requests, like getting card info. Any ideas?

**Comment by ukupat** [comment]
Hi! Have you provided both `trello-auth-token` and `trello-api-key` values in your workflow? If yes then could you make sure  this request succeeds `curl 'https://api.trello.com/1/members/me/boards?key={yourKey}&token={yourToken}'`.

The reason why it found the card IDs is that it uses Github API and not Trello API to get this information (i.e. it requests PR description from Github and uses regex to find a Trello URL -> card ID).

**Comment by alfredbirk** [comment]
Thank you, my token was wrong. The `https://trello.com/app-key` site has updated a bit it is required to make a powerup now to get the keys.  I mistakenly used what is shown as "secret" for being token, which didn't work.

Btw, thanks for making this action. It combines the best from other actions and was just what we were looking for!
