### ISSUE TITLE
Support for multiple Boards

### ISSUE THREAD

**Issue by justwiebe** [rematocorp/trello-integration-action#68]
One of the teams in my company has multiple trello boards for a single repository (a product that we license out to multiple customers, and each customer has their own board). Would it be possible to add support for multiple Trello boards?

**Comment by ukupat** [comment]
Very good question. We have also struggled a bit with this issue. I assume that the card is already on the correct board when you create a PR? Or should the integration also move it to the correct board before moving it to the desired column?

**Comment by justwiebe** [comment]
I believe the card is already on the correct board, so option 1 would probably work great for us. Thanks!

**Comment by ukupat** [comment]
Alright! I will let you know when you can test it out :)

**Comment by ukupat** [comment]
@justwiebe please try out [v8.1.0](https://github.com/rematocorp/trello-integration-action/releases/tag/v8.1.0) and let me know if this works for your team :)

**Comment by ukupat** [comment]
Closing the issue for now. Let me know if you need any help!

**Comment by justwiebe** [comment]
@ukupat Thanks for the quick work! My team just got this up and running and it's working great for them!

**Comment by ukupat** [comment]
Great to hear that!
